import './style.css'
const BASE_PATH=new URL(/* @vite-ignore */ '../',import.meta.url).pathname.replace(/\/$/,'')
const A=new URL(/* @vite-ignore */ '../assets/',import.meta.url).pathname
const arrow='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg>'
const mail='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h18v12H3zM3 7l9 7 9-7"/></svg>'
const pin='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0z"/><circle cx="12" cy="10" r="2.5"/></svg>'

const Header=(active='')=>`<div class="topline"><span>Handgemacht in Holzminden</span><span>Einzelstücke & Großauflagen</span><span>Versand in 5–7 Werktagen</span></div><header class="header"><a class="brand" href="/" data-link aria-label="Seresas Startseite"><img src="${A}logo.png" alt="Seresas Shirt-Manufaktur by Nelly"></a><nav class="nav" aria-label="Hauptnavigation"><a href="/leistungen" data-link class="${active==='leistungen'?'active':''}">Leistungen</a><a href="/produkte" data-link class="${active==='produkte'?'active':''}">Produkte</a><a href="/ueber-uns" data-link class="${active==='ueber-uns'?'active':''}">Über uns</a><a href="/faq" data-link class="${active==='faq'?'active':''}">FAQ</a></nav><a class="header-cta" href="/kontakt" data-link>Projekt anfragen ${arrow}</a><button class="menu-btn" aria-label="Menü öffnen" aria-expanded="false"><span></span><span></span></button></header>`
const Footer=()=>`<section class="footer-cta"><div><span class="eyebrow light">Bereit für dein Projekt?</span><h2>Aus deiner Idee wird<br><em>etwas Echtes.</em></h2></div><a class="circle-link" href="/kontakt" data-link aria-label="Projekt anfragen">${arrow}</a></section><footer><div class="footer-brand"><img src="${A}logo.png" alt="Seresas"><p>Persönlich. Präzise. Mit Liebe zum Handwerk.</p></div><div><h4>Entdecken</h4><a href="/leistungen" data-link>Leistungen</a><a href="/produkte" data-link>Produkte</a><a href="/ueber-uns" data-link>Über uns</a><a href="/faq" data-link>FAQ</a></div><div><h4>Kontakt</h4><a href="mailto:info@shirt-manufaktur.com">info@shirt-manufaktur.com</a><span>Fürstenberger Str. 4<br>37603 Holzminden</span></div><div><h4>Rechtliches</h4><a href="/impressum" data-link>Impressum</a><a href="/datenschutz" data-link>Datenschutz</a><a href="/agb" data-link>AGB</a><a href="/zahlung-versand" data-link>Zahlung & Versand</a><a href="/widerruf" data-link>Widerrufsbelehrung</a><a href="/cookie-richtlinie" data-link>Cookie-Richtlinie</a></div><div class="copyright">© 2026 Seresas Shirt-Manufaktur <span>Made in Holzminden</span></div></footer>`
const process=`<section class="section process"><div class="section-head"><span class="eyebrow">So läuft’s</span><h2>Von der Idee zum<br><em>Lieblingsstück.</em></h2></div><div class="steps"><article><b>01</b><h3>Idee senden</h3><p>Motiv, Logo oder Wunsch beschreiben – am besten direkt mit Bilddatei.</p></article><article><b>02</b><h3>Beratung & Vorschau</h3><p>Wir wählen Produkt und Druckverfahren und senden eine digitale Freigabe.</p></article><article><b>03</b><h3>Wir produzieren</h3><p>Nach deiner Freigabe fertigen wir präzise und mit Blick fürs Detail.</p></article><article><b>04</b><h3>Abholen oder Versand</h3><p>In der Regel ist dein Auftrag nach 5–7 Werktagen bereit.</p></article></div></section>`
const PageHero=(eyebrow,title,text,image,cls='')=>`<section class="page-hero ${cls}"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${text}</p></div>${image?`<img src="${A+image}" alt="">`:''}</section>`

const Home=()=>`${Header()}<main><section class="hero-home"><img src="${A}hero.jpeg" alt="Individuell bedruckte Shirts von Seresas"><div class="hero-shade"></div><div class="hero-copy"><span class="eyebrow light">Shirt-Manufaktur · Holzminden</span><h1>Deine Idee.<br><em>Dein Statement.</em></h1><p>Textildruck, Werbetechnik und persönliche Geschenkideen – hochwertig gefertigt, individuell für dich.</p><div class="hero-actions"><a class="button orange" href="/kontakt" data-link>Projekt starten ${arrow}</a><a class="text-link light" href="/leistungen" data-link>Unsere Möglichkeiten ${arrow}</a></div></div><div class="hero-note"><b>Seit 2011</b><span>Qualität aus dem<br>Weserbergland</span></div></section>
<section class="intro section"><div><span class="eyebrow">Was uns ausmacht</span><h2>Wir drucken nicht einfach.<br>Wir machen <em>Ideen tragbar.</em></h2></div><div class="intro-copy"><p>Ob Einzelstück, Teamausstattung oder große Auflage: Bei Seresas bekommst du ehrliche Beratung, hochwertige Materialien und das passende Verfahren für dein Motiv.</p><a class="text-link" href="/ueber-uns" data-link>Mehr über uns ${arrow}</a></div></section>
<section class="services section"><div class="section-head row"><div><span class="eyebrow">Unsere Leistungen</span><h2>Alles, was Eindruck macht.</h2></div><a class="text-link" href="/leistungen" data-link>Alle Leistungen ${arrow}</a></div><div class="service-grid"><a href="/leistungen#textildruck" data-link class="service-card featured"><img src="${A}workshop.png" alt="Textildruck in der Seresas Werkstatt"><span class="card-index">01</span><div><h3>Textildruck</h3><p>DTF, Siebdruck, Plottdruck und Sublimation – passend zu Motiv, Material und Auflage.</p><span class="card-arrow">${arrow}</span></div></a><a href="/leistungen#grossformat" data-link class="service-card dark"><span class="card-index">02</span><div><h3>Großformat<br>& Werbetechnik</h3><p>Banner, Folien, Aufkleber, Poster und CAD-Pläne bis 44 Zoll.</p><span class="card-arrow">${arrow}</span></div></a><a href="/leistungen#laser" data-link class="service-card orange-card"><span class="card-index">03</span><div><h3>Lasergravur</h3><p>Präzise Veredelung für Becher, Gläser, Metall und viele weitere Oberflächen.</p><span class="card-arrow">${arrow}</span></div></a></div></section>
<section class="audiences section"><div class="audience-title"><span class="eyebrow light">Für wen wir arbeiten</span><h2>So individuell<br>wie <em>du.</em></h2></div><div class="audience-list"><article><span>01</span><div><h3>Unternehmen</h3><p>Arbeitskleidung, Teamausstattung und Werbegeschenke mit deinem Firmenlogo.</p></div></article><article><span>02</span><div><h3>Vereine</h3><p>Einheitlicher Auftritt für Mannschaft, Mitglieder, Fans und Events.</p></div></article><article><span>03</span><div><h3>Privatpersonen</h3><p>Persönliche Statements und Geschenke für jeden besonderen Anlass.</p></div></article></div></section>
<section class="quality section"><div class="quality-image"><img src="${A}product-1.jpeg" alt="Farbmuster für hochwertige Druckergebnisse"><span>100%</span></div><div class="quality-copy"><span class="eyebrow">Qualität, die bleibt</span><h2>Gute Ideen verdienen<br><em>gute Materialien.</em></h2><p>Unsere Shirts bestehen – Sportkleidung ausgenommen – aus 100 % Baumwolle. Die eingesetzten Druckverfahren sind OEKO-TEX® STANDARD 100 zertifiziert und auf lange Haltbarkeit ausgelegt.</p><ul><li>Größen von Kindergrößen bis 8XL</li><li>Keine Mindestbestellmenge</li><li>Persönliche Beratung vor Ort</li><li>Viele Produkte „Made in Germany“</li></ul></div></section>${process}</main>${Footer()}`

const Leistungen=()=>`${Header('leistungen')}<main>${PageHero('Produkte & Leistungen','Druck, der <em>bleibt.</em>','Von Textilien über Werbetechnik bis zur Lasergravur: Wir finden das Verfahren, das zu deinem Motiv, Material und Budget passt.','screenprint.png','split')}<section class="section technique-intro"><span class="eyebrow">Unsere Verfahren</span><h2>Für jede Idee die<br><em>richtige Technik.</em></h2><p>Moderne Verfahren, satte Farben und saubere Ergebnisse – auf Wunsch beraten wir dich persönlich von der Dateiprüfung bis zur fertigen Produktion.</p></section><section class="techniques section"><article id="textildruck"><b>01</b><h3>DTF-Druck</h3><p>Perfekt für detailreiche, farbintensive Motive. Flexibel, farbecht und ideal für komplexe Designs – auch bei kleinen Stückzahlen.</p><span>Textilien · Vollfarbe · Einzelstücke</span></article><article><b>02</b><h3>Siebdruck</h3><p>Die starke Wahl für einfache Motive und größere Mengen. Besonders langlebig, deckend und wirtschaftlich.</p><span>Textilien · Serien · Langlebig</span></article><article><b>03</b><h3>Plottdruck</h3><p>Klare Konturen für Schriftzüge, Nummern und reduzierte Motive. Präzise und besonders robust.</p><span>Textilien · Namen · Logos</span></article><article><b>04</b><h3>Sublimation</h3><p>Widerstandsfähige, brillante Motive für Tassen, Funktionskleidung und passende Accessoires.</p><span>Trinkgefäße · Polyester · Farbe</span></article><article id="grossformat"><b>05</b><h3>Großformat</h3><p>Bis 44 Zoll (1118 mm): Bilder, Poster, CAD-Pläne, Banner, Planen, Folien und Aufkleber in hochwertiger Qualität.</p><span>Werbung · Papier · Folie</span></article><article id="laser"><b>06</b><h3>Lasergravur</h3><p>Dauerhafte Veredelung für Becher, Gläser, Metall und viele weitere Oberflächen – präzise mit Motiv, Logo oder Text.</p><span>Metall · Glas · Geschenkideen</span></article></section><section class="advice section"><img src="${A}about.jpg" alt="Gravurlaser bei der Fertigung gravierter Anhänger"><div><span class="eyebrow light">Nicht sicher, was passt?</span><h2>Wir beraten.<br>Du entscheidest.</h2><p>Material, Farben, Größe, Auflage und Motiv bestimmen gemeinsam das beste Verfahren. Schick uns deine Idee – wir empfehlen dir transparent die passende Lösung.</p><a class="button white" href="/kontakt" data-link>Beratung anfragen ${arrow}</a></div></section>${process}</main>${Footer()}`

const productGroups=[['Kleidung','T-Shirts · Hoodies · Sporttrikots · Funktionskleidung · UV-Kleidung'],['Trinkgefäße','Tassen · Bierkrüge · Becher · Trinkflaschen'],['Taschen','Baumwolltaschen · Shopper · Umhänge- und Laptoptaschen · Freizeittaschen'],['Kopfbedeckungen','Mützen · Beanies · Schirmmützen'],['Werbetechnik','Werbeartikel · Banner · LKW-Planen · Mastfahnen · Drop-Flags'],['Geschenke','Glasuhren · Mauspads · Handy-Ladeschalen · Einkaufswagenlöser · Schlüsselanhänger']]
const Produkte=()=>`${Header('produkte')}<main>${PageHero('Unser Sortiment','Deine Leinwand.<br><em>Deine Wahl.</em>','Für den Alltag, den großen Auftritt oder als einzigartiges Geschenk: Entdecke Produkte, die wir nach deinen Wünschen personalisieren.','product-2.jpg','split reverse')}<section class="product-list section">${productGroups.map(([h,p],i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><h2>${h}</h2><p>${p}</p><a href="/kontakt" data-link aria-label="${h} anfragen">${arrow}</a></article>`).join('')}</section><section class="local-shop section"><div><span class="eyebrow light">Shop vor Ort</span><h2>Anfassen, anprobieren,<br><em>Ideen entwickeln.</em></h2></div><p>Besuche uns in Holzminden und entdecke Materialien, Schnitte und Druckmotive direkt vor Ort. Wir beraten dich persönlich und setzen deine Idee gemeinsam mit dir um.</p><a class="button orange" href="/kontakt" data-link>So findest du uns ${arrow}</a></section></main>${Footer()}`

const UeberUns=()=>`${Header('ueber-uns')}<main>${PageHero('Über Seresas','Handwerk mit<br><em>Haltung.</em>','Seit 2011 verbinden wir im Weserbergland handwerkliche Erfahrung mit moderner Technik, Kreativität und einem klaren Anspruch an Qualität.','workshop.png','split')}<section class="story section"><div><span class="eyebrow">Unsere Geschichte</span><h2>Aus Leidenschaft<br><em>gewachsen.</em></h2></div><div class="story-copy"><p>Unser Unternehmen wurde 2011 im malerischen Weserbergland gegründet – von Anfang an mit einem klaren Fokus auf Qualität und Nachhaltigkeit. Seitdem haben wir unsere Techniken kontinuierlich weiterentwickelt und verfeinert.</p><p>Heute arbeiten wir mit modernen Technologien und renommierten Künstlern, die unsere kreativen Prozesse bereichern. Tradition und Moderne gehören für uns zusammen – genauso wie persönliche Beratung und echte Freude am Handwerk.</p></div></section><section class="values section"><article><b>Mission</b><h3>Ideen werden<br>wertvolle Produkte.</h3><p>Wir schaffen Stücke, die optisch überzeugen, lange Freude machen und ein bleibendes Erlebnis schaffen.</p></article><article><b>Werte</b><h3>Qualität mit<br>Verantwortung.</h3><p>Innovation, Nachhaltigkeit und sorgfältige Verarbeitung prägen jeden Auftrag – unabhängig von der Stückzahl.</p></article><article><b>Team</b><h3>Kreative Köpfe,<br>ein Anspruch.</h3><p>Unser Team aus erfahrenen Fachleuten setzt deine Ideen aufmerksam, lösungsorientiert und persönlich um.</p></article></section><section class="testimonials section"><span class="eyebrow light">Kundenstimmen</span><div class="quote">„Liebevolles Handwerk, hinter welchem fundiertes Wissen steckt. Die Chefin nimmt sich Zeit für alle Wünsche und ihre Beratung begründet sich auf jahrelanger Erfahrung.“</div></section></main>${Footer()}`

const faqs=[['Wie lange dauert eine Bestellung?','Die Lieferzeit beträgt in der Regel 5–7 Werktage nach Designfreigabe. Bei größeren Bestellungen oder Sonderanfertigungen kann sie sich verlängern.'],['Welche Drucktechniken bietet ihr an?','Wir bieten Siebdruck, DTF-Druck, Plottdruck und Sublimationsdruck sowie Großformatdruck und Lasergravur. Je nach Material, Motiv und Menge empfehlen wir die passende Technik.'],['Kann ich mein eigenes Design verwenden?','Ja. Sende uns dein Motiv, Logo oder deine Idee. Wir prüfen die Datei und beraten dich für ein optimales Druckergebnis.'],['Welche Dateiformate kann ich senden?','Wir akzeptieren .AI, .EPS, .PDF sowie hochauflösende .PNG- oder .JPEG-Dateien. Optimal sind mindestens 300 dpi.'],['Welche Größen und Farben gibt es?','Je nach Modell führen wir Kindergrößen sowie XXS bis 8XL und eine große Auswahl an Textilfarben.'],['Gibt es eine Mindestbestellmenge?','Nein. Bei uns kannst du auch Einzelstücke bestellen. Für größere Mengen bieten wir attraktive Preisstaffelungen.'],['Wie pflege ich bedruckte Shirts?','Am besten auf links bei maximal 30 °C waschen und nicht in den Trockner geben. So bleibt der Druck lange schön.'],['Kann ich meine Bestellung noch ändern?','Bis zur Druckfreigabe kann eine Bestellung geändert oder storniert werden. Melde dich dafür bitte möglichst früh.'],['Bekomme ich vorab eine Vorschau?','Ja. Vor dem Druck erhältst du eine digitale Vorschau. Produziert wird erst nach deiner Freigabe.'],['Gibt es Konditionen für Geschäftskunden?','Ja. Wir bieten Preisstaffelungen, Corporate Merchandise, Firmenkleidung und individuelle Lösungen für Großaufträge.']]
const FAQ=()=>`${Header('faq')}<main>${PageHero('Häufige Fragen','Gut zu <em>wissen.</em>','Antworten zu Bestellung, Dateien, Druckverfahren, Größen und Pflege – klar und kompakt.','','faq-hero')}<section class="faq-wrap section"><div class="faq-side"><span class="eyebrow">FAQ</span><h2>Noch etwas<br><em>unklar?</em></h2><p>Wir helfen dir persönlich weiter.</p><a class="text-link" href="/kontakt" data-link>Frage stellen ${arrow}</a></div><div class="accordions">${faqs.map((f,i)=>`<details ${i===0?'open':''}><summary><span>${String(i+1).padStart(2,'0')}</span>${f[0]}<b>+</b></summary><p>${f[1]}</p></details>`).join('')}</div></section></main>${Footer()}`

const Kontakt=()=>`${Header('kontakt')}<main><section class="contact-hero"><div class="contact-copy"><span class="eyebrow light">Kontakt</span><h1>Lass uns deine<br><em>Idee umsetzen.</em></h1><p>Erzähl uns von deinem Projekt. Wir melden uns persönlich mit den nächsten Schritten und einer passenden Empfehlung.</p><div class="contact-direct"><a href="mailto:info@shirt-manufaktur.com">${mail}<span><small>E-Mail</small>info@shirt-manufaktur.com</span></a><div>${pin}<span><small>Adresse</small>Fürstenberger Str. 4<br>37603 Holzminden</span></div></div></div><form class="contact-form" action="mailto:info@shirt-manufaktur.com" method="post" enctype="text/plain"><div class="field"><label for="name">Name</label><input id="name" name="Name" required placeholder="Dein Name"></div><div class="field"><label for="email">E-Mail</label><input id="email" name="E-Mail" type="email" required placeholder="name@beispiel.de"></div><div class="field full"><label for="project">Worum geht es?</label><div class="custom-select" data-select><input type="hidden" id="project" name="Projekt" value="Textildruck"><button type="button" class="select-trigger" aria-haspopup="listbox" aria-expanded="false"><span>Textildruck</span><i></i></button><div class="select-menu" role="listbox" aria-label="Worum geht es?"><button type="button" role="option" aria-selected="true" data-value="Textildruck">Textildruck</button><button type="button" role="option" aria-selected="false" data-value="Großformat & Werbetechnik">Großformat & Werbetechnik</button><button type="button" role="option" aria-selected="false" data-value="Lasergravur">Lasergravur</button><button type="button" role="option" aria-selected="false" data-value="Geschenkidee">Geschenkidee</button><button type="button" role="option" aria-selected="false" data-value="Etwas anderes">Etwas anderes</button></div></div></div><div class="field full"><label for="message">Erzähl uns von deiner Idee</label><textarea id="message" name="Nachricht" rows="5" required placeholder="Produkt, Stückzahl, Termin und alles, was wir wissen sollten …"></textarea></div><label class="privacy-check"><input type="checkbox" name="Datenschutz akzeptiert" required><span>Ich habe die <a href="/datenschutz" data-link>Datenschutzerklärung</a> gelesen und bin mit der Verarbeitung meiner Angaben zur Bearbeitung der Anfrage einverstanden.</span></label><button class="button orange" type="submit">Anfrage senden ${arrow}</button><p class="form-note">Für Design-Wünsche kannst du deine Bilddatei direkt an die E-Mail anhängen.</p></form></section><section class="visit section"><div><span class="eyebrow">Vor Ort</span><h2>Besuch uns in<br><em>Holzminden.</em></h2></div><div><p>Materialien ansehen, Schnitte vergleichen und direkt beraten lassen: In unserem Shop entwickeln wir deine Idee gemeinsam.</p><a class="text-link" href="https://maps.google.com/?q=Fürstenberger+Str.+4,+37603+Holzminden" target="_blank">Route öffnen ${arrow}</a></div></section></main>${Footer()}`

const LegalPage=(title,updated,content)=>`${Header()}<main><section class="legal-hero"><span class="eyebrow">Rechtliches</span><h1>${title}</h1><p>Stand: ${updated}</p></section><article class="legal-content">${content}</article></main>${Footer()}`

const Impressum=()=>LegalPage('Impressum','September 2026',`
  <h2>Gesetzliche Anbieterkennung</h2>
  <p><strong>Seresas Shirt-Manufaktur</strong><br>Inh. Nelly Aleksandra Tegtmeier<br>Markt 8<br>37603 Holzminden, Deutschland</p>
  <h2>Kontakt</h2>
  <p>Telefon: <a href="tel:+4955318188180">05531 8188180</a><br>Telefon: <a href="tel:+495535347">05535 347</a><br>E-Mail: <a href="mailto:info@shirt-manufaktur.com">info@shirt-manufaktur.com</a></p>
  <h2>Steuerangaben</h2><p>Steuernummer: 22/242/73058-DE358946734</p>
  <h2>Öffnungszeiten</h2><p>Montag bis Donnerstag: 10:00–17:00 Uhr<br>Freitag bis Sonntag: geschlossen</p>
  <h2>Berufshaftpflichtversicherung</h2><p>Rhion Versicherung AG<br>Postfach 10 12 49<br>41412 Neuss</p><p>Räumlicher Geltungsbereich der Berufshaftpflichtversicherung: EU bzw. europaweit.</p>
  <h2>Alternative Streitbeilegung</h2><p>Die Europäische Kommission stellt eine Plattform für die außergerichtliche Online-Streitbeilegung bereit. Die Plattform ist unter <a href="https://ec.europa.eu/odr" target="_blank" rel="noopener">ec.europa.eu/odr</a> erreichbar.</p><p>Wir sind seit dem 28.05.2020 Mitglied der Initiative „FairCommerce“. Weitere Informationen finden Sie unter <a href="https://www.fair-commerce.de" target="_blank" rel="noopener">fair-commerce.de</a>.</p>`)

const AGB=()=>LegalPage('Allgemeine Geschäftsbedingungen','04. Juni 2020',`
  <h2>Allgemeine Geschäftsbedingungen und Kundeninformationen</h2>
  <h3>I. Allgemeine Geschäftsbedingungen</h3>
  <h3>§ 1 Grundlegende Bestimmungen</h3>
  <p>(1) Die nachstehenden Geschäftsbedingungen gelten für Verträge, die Sie mit uns als Anbieter (Nelly Aleksandra Tegtmeier) über die Internetseite https://www.seresas.com schließen. Soweit nicht anders vereinbart, wird der Einbeziehung gegebenenfalls von Ihnen verwendeter eigener Bedingungen widersprochen.</p>
  <p>(2) Verbraucher im Sinne der nachstehenden Regelungen ist jede natürliche Person, die ein Rechtsgeschäft zu Zwecken abschließt, die überwiegend weder ihrer gewerblichen noch ihrer selbständigen beruflichen Tätigkeit zugerechnet werden kann. Unternehmer ist jede natürliche oder juristische Person oder eine rechtsfähige Personengesellschaft, die bei Abschluss eines Rechtsgeschäfts in Ausübung ihrer selbständigen beruflichen oder gewerblichen Tätigkeit handelt.</p>
  <h3>§ 2 Zustandekommen des Vertrages</h3>
  <p>(1) Gegenstand des Vertrages ist der Verkauf von Waren.</p>
  <p>(2) Bereits mit dem Einstellen des jeweiligen Produkts auf unserer Internetseite unterbreiten wir Ihnen ein verbindliches Angebot zum Abschluss eines Vertrages zu den in der Artikelbeschreibung angegebenen Bedingungen.</p>
  <p>(3) Der Vertrag kommt über das Online-Warenkorbsystem wie folgt zustande:</p>
  <p>Die zum Kauf beabsichtigten Waren werden in den „Warenkorb“ gelegt. Über die entsprechende Schaltfläche in der Navigationsleiste können Sie den Warenkorb aufrufen und dort jederzeit Änderungen vornehmen. Nach Aufrufen der Seite „Kasse“ und der Eingabe der persönlichen Daten sowie der Zahlungs- und Versandbedingungen werden abschließend nochmals alle Bestelldaten auf der Bestellübersichtsseite angezeigt.</p>
  <p>Soweit Sie als Zahlungsart ein Sofortzahl-System, beispielsweise PayPal, PayPal Express, Amazon Payments oder Sofort, nutzen, werden Sie entweder in unserem Online-Shop auf die Bestellübersichtsseite geführt oder zunächst auf die Internetseite des jeweiligen Anbieters weitergeleitet. Dort nehmen Sie die entsprechende Auswahl beziehungsweise Eingabe Ihrer Daten vor. Abschließend werden Sie zurück in unseren Online-Shop zur Bestellübersichtsseite geleitet.</p>
  <p>Vor dem Absenden der Bestellung haben Sie die Möglichkeit, sämtliche Angaben nochmals zu überprüfen, zu ändern – auch über die Zurück-Funktion des Internetbrowsers – oder den Kauf abzubrechen.</p>`)

const ZahlungVersand=()=>LegalPage('Zahlung & Versand','September 2026',`
  <p>Es gelten folgende Bedingungen:</p>
  <h2>Versandbedingungen</h2>
  <p>Die Lieferung erfolgt im Inland (Deutschland) sowie in Länder der Europäischen Union.</p>
  <h3>Versandkosten innerhalb Deutschlands</h3>
  <ul><li>DHL bis 2 kg: 6,99 €</li><li>DHL bis 5 kg: 7,99 €</li><li>DHL bis 10 kg: 9,49 €</li></ul>
  <p>Ab einem Bestellwert von 150,00 € liefern wir innerhalb Deutschlands versandkostenfrei.</p>
  <h3>Lieferungen ins Ausland</h3><p>Versandkosten auf Anfrage. Ab einem Bestellwert von 250,00 € liefern wir ins Ausland versandkostenfrei.</p>
  <h2>Lieferfristen</h2><p>Soweit im jeweiligen Angebot keine andere Frist angegeben ist, erfolgt die Lieferung innerhalb Deutschlands in 3–5 Tagen, bei Auslandslieferungen in 5–7 Tagen nach Vertragsschluss. Bei vereinbarter Vorauszahlung beginnt die Frist nach Ihrer Zahlungsanweisung.</p><p>An Sonn- und Feiertagen erfolgt keine Zustellung. Wenn Artikel mit unterschiedlichen Lieferzeiten bestellt werden, versenden wir die Ware in einer gemeinsamen Sendung, sofern nichts anderes vereinbart wurde. In diesem Fall richtet sich die Lieferzeit nach dem Artikel mit der längsten Lieferzeit.</p>
  <h2>Akzeptierte Zahlungsmöglichkeiten</h2><ul><li>PayPal Express</li><li>Vorkasse</li></ul><p>Bei Fragen finden Sie unsere Kontaktdaten im <a href="/impressum" data-link>Impressum</a>.</p>`)

const CookieRichtlinie=()=>LegalPage('Cookie-Richtlinie','September 2026',`
  <h2>Cookie-Einstellungen</h2><p>Diese Website verwendet technisch notwendige Cookies, damit grundlegende Funktionen zuverlässig bereitgestellt werden können. Optionale Cookies dürfen nur mit Ihrer Zustimmung verwendet werden.</p><p>Sie können Ihre Cookie-Einstellungen jederzeit über die Einstellungen Ihres Browsers prüfen, ändern oder gespeicherte Cookies löschen. Wenn Sie Cookies deaktivieren, stehen möglicherweise nicht alle Funktionen der Website uneingeschränkt zur Verfügung.</p><h2>Weitere Informationen</h2><p>Informationen zum Umgang mit personenbezogenen Daten und zu Ihren Rechten finden Sie in der Datenschutzerklärung der Seresas Shirt-Manufaktur.</p>`)

const Datenschutz=()=>LegalPage('Datenschutzerklärung','25. September 2026',`
  <h2>1. Verantwortlicher</h2><p>Verantwortlich für die Datenverarbeitung auf dieser Website ist:<br><strong>Seresas Shirt-Manufaktur</strong><br>Inhaberin: Nelly Aleksandra Tegtmeier<br>Markt 8, 37603 Holzminden<br>Telefon: 05531 8188180<br>E-Mail: <a href="mailto:info@shirt-manufaktur.com">info@shirt-manufaktur.com</a></p>
  <h2>2. Allgemeine Hinweise</h2><p>Personenbezogene Daten sind alle Informationen, die sich auf eine identifizierte oder identifizierbare Person beziehen. Soweit nachfolgend nichts anderes angegeben ist, ist die Bereitstellung Ihrer Daten weder gesetzlich noch vertraglich vorgeschrieben. Sie sind nicht verpflichtet, Daten bereitzustellen. Ohne erforderliche Angaben können einzelne Leistungen, insbesondere die Bearbeitung einer Anfrage oder Bestellung, jedoch nicht erbracht werden.</p>
  <h2>3. Hosting und Server-Protokolle</h2><p>Beim Aufruf dieser Website werden technisch erforderliche Daten durch den Hosting- und IT-Dienstleister verarbeitet. Dazu können IP-Adresse, Datum und Uhrzeit, aufgerufene Seite, übertragene Datenmenge, Referrer, Browser, Betriebssystem und anfragender Provider gehören. Die Verarbeitung erfolgt zur sicheren, stabilen und fehlerfreien Bereitstellung der Website auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Unser berechtigtes Interesse liegt im zuverlässigen und sicheren Betrieb dieses Angebots.</p>
  <h2>4. Kontaktaufnahme und Kontaktformular</h2><p>Wenn Sie uns per E-Mail oder über das Kontaktformular ansprechen, verarbeiten wir die von Ihnen mitgeteilten Angaben – insbesondere Name, E-Mail-Adresse, Projektart und Nachricht – ausschließlich zur Bearbeitung Ihrer Anfrage und möglicher Anschlussfragen. Das Formular öffnet zum Versand das auf Ihrem Gerät eingerichtete E-Mail-Programm; die eingegebenen Angaben werden nicht vorab in einer eigenen Formulardatenbank dieser Website gespeichert.</p><p>Die Verarbeitung erfolgt bei vorvertraglichen oder vertraglichen Anliegen auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO, im Übrigen auf Grundlage Ihrer Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO beziehungsweise unseres berechtigten Interesses an der Bearbeitung Ihrer Anfrage gemäß Art. 6 Abs. 1 lit. f DSGVO. Eine erteilte Einwilligung können Sie jederzeit mit Wirkung für die Zukunft widerrufen.</p><p>Wir speichern Anfragen nur so lange, wie dies für die Bearbeitung und gesetzliche Aufbewahrungspflichten erforderlich ist.</p>
  <h2>5. Bestellungen und Vertragsabwicklung</h2><p>Bei Bestellungen verarbeiten wir personenbezogene Daten, soweit dies zur Anbahnung, Durchführung und Abwicklung des Vertrages erforderlich ist. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO. Soweit erforderlich, geben wir Daten in dem notwendigen Umfang an Versandunternehmen, Zahlungsdienstleister, Anbieter der Bestellabwicklung und IT-Dienstleister weiter.</p>
  <h2>6. Zahlungsdienstleister</h2><h3>PayPal und PayPal Express</h3><p>Bei Auswahl von PayPal werden die zur Zahlungsabwicklung notwendigen Daten an PayPal (Europe) S.à r.l. et Cie, S.C.A., 22–24 Boulevard Royal, L-2449 Luxemburg, übermittelt. Die Verarbeitung erfolgt zur Vertragsabwicklung gemäß Art. 6 Abs. 1 lit. b DSGVO. Bei der Einbindung von PayPal Express können mit Ihrer Einwilligung zusätzlich technische Daten und Cookies verarbeitet werden. Weitere Informationen finden Sie in der <a href="https://www.paypal.com/de/webapps/mpp/ua/privacy-full" target="_blank" rel="noopener">Datenschutzerklärung von PayPal</a>.</p>
  <h2>7. Cookies und lokale Speicherung</h2><p>Diese Website verwendet derzeit ausschließlich technisch notwendige Speicherungen. Ihre Auswahl im Cookie-Hinweis wird lokal in Ihrem Browser gespeichert, damit der Hinweis nicht bei jedem Seitenaufruf erneut erscheint. Diese Information enthält keine Angaben zu Ihrer Person und wird nicht zu Werbe- oder Analysezwecken genutzt.</p><p>Technisch notwendige Verarbeitungen erfolgen auf Grundlage von § 25 Abs. 2 Nr. 2 TDDDG und Art. 6 Abs. 1 lit. f DSGVO. Optionale Analyse- oder Marketingdienste werden ohne Ihre vorherige Einwilligung nicht aktiviert. Einzelheiten finden Sie in der <a href="/cookie-richtlinie" data-link>Cookie-Richtlinie</a>.</p>
  <h2>8. Externe Links und Kartendienst</h2><p>Die Website enthält Links zu externen Angeboten, etwa Google Maps zur Routenplanung. Erst wenn Sie einen solchen Link öffnen, verlassen Sie diese Website. Für die anschließende Datenverarbeitung ist der jeweilige Anbieter verantwortlich.</p>
  <h2>9. Speicherdauer</h2><p>Nach vollständiger Vertragsabwicklung werden Daten zunächst für die Dauer gesetzlicher Gewährleistungs-, steuer- und handelsrechtlicher Aufbewahrungsfristen gespeichert und anschließend gelöscht, sofern keine Einwilligung oder andere Rechtsgrundlage eine längere Verarbeitung erlaubt.</p>
  <h2>10. Ihre Rechte</h2><p>Bei Vorliegen der gesetzlichen Voraussetzungen haben Sie nach Art. 15 bis 21 DSGVO insbesondere das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch. Eine erteilte Einwilligung können Sie jederzeit für die Zukunft widerrufen. Wenden Sie sich hierfür an die oben genannte Kontaktadresse.</p>
  <h2>11. Beschwerderecht</h2><p>Sie haben gemäß Art. 77 DSGVO das Recht, sich bei einer Datenschutzaufsichtsbehörde zu beschweren, wenn Sie der Ansicht sind, dass die Verarbeitung Ihrer personenbezogenen Daten nicht rechtmäßig erfolgt.</p>
  <h2>12. Widerspruchsrecht</h2><p>Beruht eine Verarbeitung auf Art. 6 Abs. 1 lit. f DSGVO, können Sie aus Gründen, die sich aus Ihrer besonderen Situation ergeben, jederzeit mit Wirkung für die Zukunft widersprechen. Wir beenden die Verarbeitung, sofern keine zwingenden schutzwürdigen Gründe oder Gründe zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen entgegenstehen.</p>`)

const Widerruf=()=>LegalPage('Widerrufsbelehrung','25. September 2026',`
  <p><strong>Widerrufsrecht für Verbraucher</strong></p><p>Verbraucher ist jede natürliche Person, die ein Rechtsgeschäft zu Zwecken abschließt, die überwiegend weder ihrer gewerblichen noch ihrer selbstständigen beruflichen Tätigkeit zugerechnet werden können.</p>
  <h2>Widerrufsrecht</h2><p>Sie haben das Recht, binnen vierzehn (14) Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen.</p><p>Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag, an dem Sie oder ein von Ihnen benannter Dritter, der nicht der Beförderer ist, die Ware in Besitz genommen haben beziehungsweise hat, sofern Sie eine oder mehrere Waren im Rahmen einer einheitlichen Bestellung bestellt haben und diese einheitlich geliefert werden.</p>
  <p>Um Ihr Widerrufsrecht auszuüben, müssen Sie uns mittels einer eindeutigen Erklärung – beispielsweise per Brief oder E-Mail – über Ihren Entschluss informieren:</p><p><strong>Shirtmanufaktur</strong><br>Inhaberin: Nelly Aleksandra Tegtmeier<br>Markt 8<br>37603 Holzminden<br>Telefon: 05531 8188180<br>E-Mail: <a href="mailto:info@shirt-manufaktur.com">info@shirt-manufaktur.com</a></p><p>Sie können dafür das nachstehende Muster-Widerrufsformular verwenden; dies ist jedoch nicht vorgeschrieben. Zur Wahrung der Frist reicht es aus, dass Sie die Mitteilung vor Ablauf der Widerrufsfrist absenden.</p>
  <h2>Folgen des Widerrufs</h2><p>Wir erstatten die erhaltenen Zahlungen einschließlich der Kosten der von uns angebotenen günstigsten Standardlieferung unverzüglich und spätestens binnen vierzehn Tagen ab Eingang Ihrer Widerrufsmitteilung. Für die Rückzahlung verwenden wir dasselbe Zahlungsmittel wie bei der ursprünglichen Transaktion, sofern nichts anderes vereinbart wurde. Ihnen werden wegen der Rückzahlung keine Entgelte berechnet.</p><p>Wir können die Rückzahlung verweigern, bis wir die Waren zurückerhalten haben oder Sie den Nachweis der Rücksendung erbracht haben – je nachdem, welcher Zeitpunkt früher eintritt.</p><p>Sie haben die Waren unverzüglich und spätestens binnen vierzehn Tagen ab Ihrer Widerrufsmitteilung zurückzusenden oder zu übergeben. Die Frist ist gewahrt, wenn Sie die Waren rechtzeitig absenden. Sie tragen die unmittelbaren Kosten der Rücksendung. Für einen Wertverlust müssen Sie nur aufkommen, wenn dieser auf einen zur Prüfung von Beschaffenheit, Eigenschaften und Funktionsweise nicht notwendigen Umgang zurückzuführen ist.</p>
  <h2>Ausschluss des Widerrufsrechts</h2><p>Das Widerrufsrecht besteht gemäß § 312g Abs. 2 Nr. 1 BGB insbesondere nicht bei Waren, die nicht vorgefertigt sind und für deren Herstellung eine individuelle Auswahl oder Bestimmung maßgeblich ist oder die eindeutig auf persönliche Bedürfnisse zugeschnitten sind.</p><p>Dies betrifft insbesondere individuell gestaltete oder personalisierte Produkte wie bedruckte T-Shirts, Hoodies und sonstige Textilien, Tassen, Banner, Aufkleber, Werbeartikel, Fotogeschenke und Gravuren. Für solche individuell angefertigten Produkte besteht nach Vertragsschluss kein gesetzliches Widerrufsrecht.</p>
  <h2>Muster-Widerrufsformular</h2><p>Wenn Sie den Vertrag widerrufen möchten, füllen Sie dieses Formular aus und senden Sie es an die oben genannte Adresse:</p><div class="legal-form"><p>Hiermit widerrufe(n) ich/wir (*) den von mir/uns (*) abgeschlossenen Vertrag über den Kauf der folgenden Waren (*) / die Erbringung der folgenden Dienstleistung (*):</p><p>Bestellt am (*) / erhalten am (*):</p><p>Name des/der Verbraucher(s):</p><p>Anschrift des/der Verbraucher(s):</p><p>Unterschrift des/der Verbraucher(s) – nur bei Mitteilung auf Papier:</p><p>Datum:</p><p><small>(*) Unzutreffendes streichen.</small></p></div>`)

const routes={'/':Home,'/leistungen':Leistungen,'/produkte':Produkte,'/ueber-uns':UeberUns,'/faq':FAQ,'/kontakt':Kontakt,'/impressum':Impressum,'/datenschutz':Datenschutz,'/agb':AGB,'/zahlung-versand':ZahlungVersand,'/widerruf':Widerruf,'/cookie-richtlinie':CookieRichtlinie}
function initEnhancements(){
  const animated=document.querySelectorAll('main section > *, .service-card, .techniques article, .product-list article, .values article')
  if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver' in window){
    animated.forEach(el=>el.classList.add('reveal'))
    const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('revealed');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -35px'})
    animated.forEach(el=>observer.observe(el))
  }
  document.querySelectorAll('[data-select]').forEach(select=>{
    const trigger=select.querySelector('.select-trigger'),menu=select.querySelector('.select-menu'),input=select.querySelector('input'),options=[...menu.querySelectorAll('[role="option"]')]
    const close=()=>{select.classList.remove('open');trigger.setAttribute('aria-expanded','false')}
    const choose=option=>{input.value=option.dataset.value;trigger.querySelector('span').textContent=option.dataset.value;options.forEach(item=>item.setAttribute('aria-selected',String(item===option)));close();trigger.focus()}
    trigger.addEventListener('click',()=>{const open=select.classList.toggle('open');trigger.setAttribute('aria-expanded',String(open));if(open) options.find(option=>option.getAttribute('aria-selected')==='true').focus()})
    options.forEach((option,index)=>{option.addEventListener('click',()=>choose(option));option.addEventListener('keydown',event=>{if(event.key==='ArrowDown'){event.preventDefault();options[(index+1)%options.length].focus()}if(event.key==='ArrowUp'){event.preventDefault();options[(index-1+options.length)%options.length].focus()}if(event.key==='Escape'){close();trigger.focus()}if(event.key==='Enter'||event.key===' '){event.preventDefault();choose(option)}})})
    document.addEventListener('click',event=>{if(!select.contains(event.target))close()})
  })
  if(!localStorage.getItem('seresas-cookie-choice')){
    const notice=document.createElement('aside');notice.className='cookie-notice';notice.setAttribute('aria-label','Cookie-Hinweis');notice.innerHTML=`<div><strong>Deine Privatsphäre</strong><p>Wir verwenden nur technisch notwendige Speicherungen, damit diese Website zuverlässig funktioniert. Optionale Dienste werden nur mit deiner Zustimmung aktiviert.</p><a href="/cookie-richtlinie">Mehr erfahren</a></div><div class="cookie-actions"><button data-choice="necessary">Nur notwendige</button><button class="accept" data-choice="all">Alle akzeptieren</button></div>`;document.body.appendChild(notice)
    notice.querySelector('a').addEventListener('click',e=>{e.preventDefault();history.pushState({},'','/cookie-richtlinie');notice.remove();render();scrollTo({top:0,behavior:'smooth'})})
    notice.querySelectorAll('[data-choice]').forEach(button=>button.addEventListener('click',()=>{localStorage.setItem('seresas-cookie-choice',button.dataset.choice);notice.classList.add('closing');setTimeout(()=>notice.remove(),250)}))
  }
}
function render(){const path=location.pathname.startsWith(BASE_PATH)?location.pathname.slice(BASE_PATH.length):location.pathname;const clean=path.replace(/\/$/,'')||'/';document.querySelector('#app').innerHTML=(routes[clean]||Home)();document.title=clean==='/'?'Seresas Shirt-Manufaktur | Textildruck in Holzminden':`${clean.slice(1).replace('-',' ')} | Seresas Shirt-Manufaktur`;document.querySelectorAll('[data-link]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();history.pushState({},'',`${BASE_PATH}${a.getAttribute('href')}`);render();scrollTo({top:0,behavior:'smooth'})}));const btn=document.querySelector('.menu-btn');btn?.addEventListener('click',()=>{const open=document.body.classList.toggle('menu-open');btn.setAttribute('aria-expanded',open)});document.body.classList.remove('menu-open');initEnhancements()}
addEventListener('popstate',render);render()
